/**
 * TCE504 Exercise Metabolism — Google Sheets Backend V3
 * Bound to the destination Google Sheet.
 * Deploy as Web App: Execute as Me; Who has access: Anyone.
 */
const COURSE='TCE504';
const TOPIC='Exercise Metabolism';
const SHEETS={PRE:'Pre_Test',POST:'Post_Test',REFLECTION:'Reflection',CLINICAL:'Clinical_Application',ACTIVITY:'Activity_Log',RESPONSES:'Section_Response',TAKEAWAY:'Final_Takeaway',SUMMARY:'Student_Summary'};
function getWorkbook_(){return SpreadsheetApp.getActiveSpreadsheet();}
function doGet(){return json_({ok:true,service:'TCE504 Exercise Metabolism Google Sheet Backend V3',time:new Date().toISOString()});}
function doPost(e){try{const raw=e&&e.postData&&e.postData.contents?e.postData.contents:'{}';const d=JSON.parse(raw);const ss=getWorkbook_();setupSheets_(ss);switch(String(d.type||'').toLowerCase()){case'pretest':saveQuiz_(ss,d,'pretest');break;case'posttest':saveQuiz_(ss,d,'posttest');break;case'reflection':saveReflection_(ss,d);break;case'clinical_application':saveClinical_(ss,d);break;case'activity':saveActivity_(ss,d);break;case'section_response':saveResponse_(ss,d);break;case'takeaway':saveTakeaway_(ss,d);break;default:throw new Error('Unknown submission type: '+d.type)}updateSummary_(ss,d);return json_({ok:true,type:d.type,message:'Recorded successfully',timestamp:new Date().toISOString()})}catch(err){return json_({ok:false,error:String(err)})}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function setupSheets_(ss){ensure_(ss,SHEETS.PRE,['Timestamp','Name','Matric No','USM Email','Course','Topic','Score','Percentage','Missed Questions','Answers','Record Type']);ensure_(ss,SHEETS.POST,['Timestamp','Name','Matric No','USM Email','Course','Topic','Score','Percentage','Missed Questions','Answers','Record Type']);ensure_(ss,SHEETS.REFLECTION,['Timestamp','Name','Matric No','USM Email','Course','Topic','Most Important Concept','Concept Still Unclear','Explain to Athlete/Patient/Student','Practical Application','Confidence 1-5','Question for Lecturer','Submission']);ensure_(ss,SHEETS.CLINICAL,['Timestamp','Name','Matric No','USM Email','Course','Topic','Section','Section Title','Exercise Demand','Data Interpretation','Clinical Decision','Recovery Reasoning','Final Clinical Reasoning','Self Check','Submission']);ensure_(ss,SHEETS.ACTIVITY,['Timestamp','Name','Matric No','USM Email','Course','Topic','Section','Section Title','Event']);ensure_(ss,SHEETS.RESPONSES,['Timestamp','Name','Matric No','USM Email','Course','Topic','Section','Section Title','Responses JSON','Submission']);ensure_(ss,SHEETS.TAKEAWAY,['Timestamp','Name','Matric No','USM Email','Course','Topic','Takeaway','Submission']);ensure_(ss,SHEETS.SUMMARY,['Name','Matric No','USM Email','Pre-Test %','Post-Test %','Learning Gain','Reflection','Confidence','Clinical Application','Last Activity','Status'])}
function ensure_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(headers);else{const current=sh.getRange(1,1,1,headers.length).getValues()[0];if(current.join('||')!==headers.join('||'))sh.getRange(1,1,1,headers.length).setValues([headers])}sh.setFrozenRows(1);return sh}
function base_(d){return [new Date(d.timestamp||new Date()),d.name||'',d.matric||'',d.email||'',d.course||COURSE,d.topic||TOPIC]}
function saveQuiz_(ss,d,type){const sh=ss.getSheetByName(type==='pretest'?SHEETS.PRE:SHEETS.POST);sh.appendRow(base_(d).concat([d.score||'',d.percentage||'',d.missed||'',JSON.stringify(d.answers||[]),type]))}
function saveReflection_(ss,d){ss.getSheetByName(SHEETS.REFLECTION).appendRow(base_(d).concat([d.reflection1||'',d.reflection2||'',d.reflection3||'',d.reflection4||'',d.confidence||'',d.question||'', 'reflection']))}
function saveClinical_(ss,d){ss.getSheetByName(SHEETS.CLINICAL).appendRow(base_(d).concat([d.section||'',d.sectionTitle||'',d.demand||'',d.dataInterpretation||'',d.decision||'',d.recovery||'',d.finalReasoning||'',JSON.stringify(d.selfCheck||[]),'clinical_application']))}
function saveActivity_(ss,d){ss.getSheetByName(SHEETS.ACTIVITY).appendRow(base_(d).concat([d.section||'',d.sectionTitle||'',d.event||'Section opened']))}
function saveResponse_(ss,d){ss.getSheetByName(SHEETS.RESPONSES).appendRow(base_(d).concat([d.section||'',d.sectionTitle||'',d.responses||'[]','section_response']))}
function saveTakeaway_(ss,d){ss.getSheetByName(SHEETS.TAKEAWAY).appendRow(base_(d).concat([d.takeaway||'','takeaway']))}
function updateSummary_(ss,d){const matric=String(d.matric||'').trim();if(!matric)return;const sh=ss.getSheetByName(SHEETS.SUMMARY);const rows=sh.getDataRange().getValues();let r=-1;for(let i=1;i<rows.length;i++){if(String(rows[i][1]).trim()===matric){r=i+1;break}}if(r<0){sh.appendRow([d.name||'',matric,d.email||'','','','','','','',new Date(),'Active']);r=sh.getLastRow()}else{if(d.name)sh.getRange(r,1).setValue(d.name);if(d.email)sh.getRange(r,3).setValue(d.email);sh.getRange(r,10).setValue(new Date());sh.getRange(r,11).setValue('Active')}const all=sh.getDataRange().getValues();let pre='',post='';for(let i=all.length-1;i>=1;i--){if(String(all[i][1]).trim()===matric){if(!pre&&all[i][3]!=='')pre=all[i][3];if(!post&&all[i][4]!=='')post=all[i][4]}}if(d.type==='pretest')pre=d.percentage||'';if(d.type==='posttest')post=d.percentage||'';if(pre!=='')sh.getRange(r,4).setValue(pre);if(post!=='')sh.getRange(r,5).setValue(post);if(pre!==''&&post!==''){const gain=Number(post)-Number(pre);sh.getRange(r,6).setValue(gain)}if(d.type==='reflection'){sh.getRange(r,7).setValue('Submitted');sh.getRange(r,8).setValue(d.confidence||'')}if(d.type==='clinical_application')sh.getRange(r,9).setValue('Submitted')}
